### ISSUE TITLE
cp target is not a directory

### ISSUE THREAD

**Issue by zrks** [Accenture/adop-docker-compose#146]
Hi team - docker-compose fails:
![image](https://cloud.githubusercontent.com/assets/7746021/18867021/2ae7545e-84ab-11e6-8995-a9eabe1e6a7f.png)

Why there is something like this in entrypoint??
![image](https://cloud.githubusercontent.com/assets/7746021/18867039/42a1d56a-84ab-11e6-8ffc-656cc904d837.png)

**Comment by mihail-dev** [comment]
Hey @zrks,Take a look at etc/volumes/default.yml (https://github.com/Accenture/adop-docker-compose/blob/master/etc/volumes/local/default.yml#L4). This is when the directory is being created. 

Because you are running the main docker-compose file, the volumes compose one is not executed and the directory is not created. The copy commands throws the error because of this. 

I would recommend using the adop cli instead. This will also fix the warning messages you are getting because it will source the variables from env.config.sh.

Also feel free to take a look at https://github.com/Accenture/adop-nginx to see how the adop-nginx image has been implemented.

**Comment by zrks** [comment]
Hi - yes already inspected that - thanks for reply!
We can close this issue then.
