### ISSUE TITLE
Custom network name parameter is ignored in startup.sh

### ISSUE THREAD

**Issue by deors** [Accenture/adop-docker-compose#28]
Currently, startup.sh script, in line 32, seems to be ignoring the custom network name parameter that, if passed through CLI (-n <name-of-the-network>) should be used instead of the default name (adopnetwork). In previous versions of the script, the assignment to the env var was correct.
Should line 32 be restored as found in previous versions? That is:
     export CUSTOM_NETWORK_NAME=${OPTARG}

**Comment by nickdgriffin** [comment]
Yeah, that looks like it has slipped through the net and is incorrect in its current form.

**Comment by nickdgriffin** [comment]
It's fixed in the new quickstart.sh that'll replace local-setup.sh and startup.sh eventually, can you give that a go instead please?

**Comment by deors** [comment]
I will take a look to the new quickstart.sh script. Is it already pushed to
GitHub repo?

**Comment by nickdgriffin** [comment]
Yes, it is on master as of last night for people to give it a go.

**Comment by deors** [comment]
I've been testing quickstart.sh but I got an error in line 47 of cmd/compose script. It seems that the "--shell bash" parameter is missing in this script and this is causing the docker-machine env command to generate Windows commands, and not Bash commands. Tested locally that after the change, a new ADOP environment is provisioned successfully. PR submitted to fix this.

**Comment by deors** [comment]
Returning to the origin of the issue. I've tested with quickstart.sh but the custom network name parameter  (-n) is not accepted by quickstart.sh and hence it is not passed onto cmd/compose script. I guess that the correct behaviour should be that quickstart.sh processes all expected/optional parameters and pass them to compose, as currently only the machine name is passed (line 132 of quickstart.sh file).

**Comment by nickdgriffin** [comment]
Well the idea behind quickstart.sh is that it's the fastest route to standing up the platform, rather than it being another layer of abstraction with a pass through for every possible thing that the CLI accepts.

The ultimate state is that only CLI commands will be used to standup the platform, and quickstart.sh is just a step towards that to bridge for docker-machine in the short term. If you want to use another network name I'd suggest not using the quickstart.sh (or startup.sh, which will get removed eventually) and instead running docker-machine by hand followed by "./adop compose init" with whatever parameters you need for the compose part.

**Comment by deors** [comment]
Ok. But I suggest having in roadmap to have an "adop create" command to encapsulate the different ways to create the base machine, local, AWS, etc. I like the simplicity it brings for people not well skilled with docker-machine or AWS CLI. Anyway, the network name is not something that people may need to hack, so it's fine to keep it simply out of scope for quickstart.

**Comment by nickdgriffin** [comment]
Yep, that's the idea. "adop provision" is going to cover that base for the various "simple" ways of launching.
