### ISSUE TITLE
Reference_Application_Deploy_ProdA failing

### ISSUE THREAD

**Issue by josequaresma** [Accenture/adop-docker-compose#94]
The Reference_Application_Deploy_ProdA task on the pre packaged example is failing for me with the following error. Am I doing something wrong when executing it?

`+ docker cp /workspace/ExampleWorkspace/ExampleProject/Reference_Application_Deploy_ProdA/target/petclinic.war ExampleWorkspace_ExampleProject_PRODA:/usr/local/tomcat/webapps/
no such directory
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE`

**Comment by anton-kasperovich** [comment]
@josequaresma there is "Create_Environment" Jenkins job in ExampleProject (this job is also visible from "Environment_Provisioning" pipeline), you have to run it with value "PROD" before actual deployment attempt from a reference application pipeline. Unfortunately, error message is not so informative, it's just because you doesn't have deployed production (PROD_A/PROD_B) configuration.

**Comment by josequaresma** [comment]
Thanks a lot for the help @anton-kasperovich , that did it!
